name: logecom
description: Simple yet powerful logger and middleware-based logging pipeline.
version: 0.0.9
homepage: https://github.com/koldoon/logecom-dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  intl: ^0.18.1
  duration: ^3.0.13

dev_dependencies:
  dartdoc:
  lints: ^3.0.0
