name: logecom
description: Simple yet powerful logger and middleware-based logging pipeline.
version: 0.0.10
homepage: https://github.com/koldoon/logecom-dart

environment:
  sdk: '>=2.13.0 <4.0.0'

dependencies:
  intl: any
  duration: ^3.0.13

dev_dependencies:
  dartdoc: any
  lints: ^3.0.0
